### ISSUE TITLE
Build fails on Unity 2021.2 or earlier

### ISSUE THREAD

**Issue by mob-sakai** [game-ci/unity-builder#752]
**Bug description**

[Build with v4](https://github.com/mob-sakai/UIDynamicSampler/actions/runs/18428863199/job/52513607386)

```
-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/UnityBuilderAction.dll
Microsoft (R) Visual C# Compiler version 3.5.0-dev-20359-01 (8da8ba0c)
Copyright (C) Microsoft Corporation. All rights reserved.

Assets/Editor/Editor/UnityBuilderAction/Input/AndroidSettings.cs(141,17): error CS1501: No overload for method 'TryParse' takes 4 arguments
```

**How to reproduce**

- Build a legacy project (that uses C#6)

**Expected behavior**

- The build succeeds.

**Additional details**

- This is probably affected by this PR: https://github.com/game-ci/unity-builder/pull/738
  - `out var` requires C#7 or higher and won't affect modern projects.
  - Temporarily, you can work around the issue by using the version before that PR merge (v4.5.0).
    - [Build with v4.5.0](https://github.com/mob-sakai/UIDynamicSampler/actions/runs/18428790043/job/52513444140)
- Is there a plan to deprecate support for older projects?

**Comment by webbertakken** [comment]
> Is there a plan to deprecate support for older projects?

In the past we've tried to deprecate some versions, but in the game industry and especially with Unity it happens fairly often that projects get completely stuck to a certain engine version.

When Unity offers LTS still for those versions we should probably support it.

PRs welcome to downgrade the `TryParse` syntax.

**Comment by mob-sakai** [comment]
Sorry, some of my explanations were incorrect.
- The API that actually caused the problem was `Enum.TryParse`.
  - https://github.com/game-ci/unity-builder/commit/9cd9f7e0e726533dbeeea33f8cb2c5ccdcfa00cd#diff-dd59336916ef692ec745dd00ea2ded5f03766006befc531d5362a202c2691ac8R141
  - This API was added in `.Net Standard 2.1` and is available from Unity 2021.3 onwards.
  - This API was only used in `#if UNITY_6000_0_OR_NEWER`.
- C#7 support started in Unity 2018.3.
